version: 1.0.1.{build}
os: Visual Studio 2022

# Only focus on the Main branch
branches:
  only:
  - main

install:

build_script:
- cmd: dotnet --info
- cmd: dotnet tool restore
- cmd: dotnet cake

test: off

artifacts:
- path: artifacts/zip/*.zip
- path: artifacts/nuget/*.nupkg